services:
  caddy:
    image: caddy:2.9-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./web:/srv/web:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - default
      - snhgn-network

volumes:
  caddy_data:
  caddy_config:

networks:
  default:
    driver: bridge
  snhgn-network:
    external: true
