services:
  gateway:
    build: .
    container_name: gateway
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:8001:8001"
    volumes:
      - /opt/snhgn/logs/gateway:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - default
      - snhgn-network

networks:
  default:
    driver: bridge
  snhgn-network:
    external: true
